Bf.module {// RUN: python C:\Projects\2023\infoBf.decrementba\Sourcen\mlir_bf\tools\bfBf.decrementtoBf.decrementmlir_bfBf.outputpy translate bfBf.decrementtoBf.decrementmlirBf.decrementbf Bf.decrementBf.decrementoutputBf.decrementpath="" %s Bf.shift_right %t
// RUN: BfBf.decrementopt %t Bf.decrementBf.decrementbfBf.decrementtoBf.decrementllvm Bf.shift_right %t1
// RUN: BfBf.decrementtranslate %t1 Bf.decrementBf.decrementmlirBf.decrementtoBf.decrementllvmir Bf.shift_right %t2
// RUN: clang %t2 Bf.shift_right %t3
// RUN: %t3 Bf.shift_right %t4
// RUN: FileCheck %t4 Bf.shift_left hello_worldBf.outputsem


Bf.shift_rightBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.increment Bf.loop {  Bf.shift_left  Bf.increment  Bf.increment  Bf.increment  Bf.increment  Bf.increment  Bf.increment  Bf.increment  Bf.increment  Bf.shift_right  Bf.decrement  }Bf.shift_leftBf.outputBf.shift_rightBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.loop {Bf.shift_leftBf.incrementBf.incrementBf.incrementBf.incrementBf.shift_rightBf.decrement }Bf.shift_leftBf.incrementBf.outputBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.outputBf.outputBf.incrementBf.incrementBf.incrementBf.outputBf.loop {Bf.decrement }
Bf.shift_rightBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.loop {Bf.shift_leftBf.incrementBf.incrementBf.incrementBf.incrementBf.shift_rightBf.decrement } Bf.shift_leftBf.outputBf.shift_rightBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.loop {Bf.shift_leftBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.shift_rightBf.decrement }Bf.shift_leftBf.decrementBf.outputBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.outputBf.incrementBf.incrementBf.increment
Bf.outputBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.outputBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.decrementBf.outputBf.loop {Bf.decrement }Bf.shift_rightBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.loop {Bf.shift_leftBf.incrementBf.incrementBf.incrementBf.incrementBf.shift_rightBf.decrement  }Bf.shift_leftBf.incrementBf.outputBf.loop {Bf.decrement }Bf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.incrementBf.output}